// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

var proxy = "PROXY 10.10.100.157:8888;";

var rules = [
    "bff.stg.starbucks.com.cn",
    "3pp.stg.starbucks.com.cn",
];

var direct = 'DIRECT;';

function FindProxyForURL(url, host) {
    if (
        (url.indexOf(rules[0]) > -1) || (url.indexOf(rules[1]) > -1)
    ) {
        return proxy
    }

    return direct
}
